{
  "comments": [
    {
      "key": {
        "uuid": "5a3f45e8_45552cc5",
        "filename": "yardstick/common/openstack_utils.py",
        "patchSetId": 5
      },
      "lineNbr": 561,
      "author": {
        "id": 1402
      },
      "writtenOn": "2018-02-23T20:53:34Z",
      "side": 1,
      "message": "does is the OpenStackCloudException exception have useful error info in the message?\n\ncan we dump the message, or maybe log.exception(\"\") if we want full traceback.",
      "revId": "5af2f4c2051ec5bfc76470a6e4569621561f02c4",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}