{
  "comments": [
    {
      "key": {
        "uuid": "da33351e_3de2b49f",
        "filename": "yardstick/benchmark/scenarios/availability/scenario_general.py",
        "patchSetId": 6
      },
      "lineNbr": 90,
      "author": {
        "id": 1402
      },
      "writtenOn": "2017-08-15T04:55:06Z",
      "side": 1,
      "message": "this is a no-op?\n\nWhy catch an exception and re-raise it, just don\u0027t catch it.",
      "revId": "d1b2f5dff16b281bbfe75fb4564f78800001400b",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da33351e_9dee608a",
        "filename": "yardstick/benchmark/scenarios/availability/serviceha.py",
        "patchSetId": 6
      },
      "lineNbr": 99,
      "author": {
        "id": 1402
      },
      "writtenOn": "2017-08-15T04:55:06Z",
      "side": 1,
      "message": "also no-op.  just don\u0027t catch the AssertionError.",
      "revId": "d1b2f5dff16b281bbfe75fb4564f78800001400b",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}