{
  "comments": [
    {
      "key": {
        "uuid": "9a3d3df0_03fd6e6e",
        "filename": "tests/unit/network_services/test_utils.py",
        "patchSetId": 7
      },
      "lineNbr": 128,
      "author": {
        "id": 6831
      },
      "writtenOn": "2017-12-14T18:00:44Z",
      "side": 1,
      "message": "regrettably this is not consistent among exceptions, hence why i convert the exception to a string: we\u0027re in deep trouble if some exception can\u0027t be converted to a string.\n\nif you really don\u0027t like converting to a string, then you want:\n\n exception.exception.args[0]",
      "range": {
        "startLine": 128,
        "startChar": 49,
        "endLine": 128,
        "endChar": 76
      },
      "revId": "e6c21a80a91919707b05ee301de990c660e24b85",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_63443ab7",
        "filename": "tests/unit/network_services/test_utils.py",
        "patchSetId": 7
      },
      "lineNbr": 128,
      "author": {
        "id": 7075
      },
      "writtenOn": "2017-12-14T18:04:46Z",
      "side": 1,
      "message": "BaseException has \"message\" as class variable",
      "parentUuid": "9a3d3df0_03fd6e6e",
      "range": {
        "startLine": 128,
        "startChar": 49,
        "endLine": 128,
        "endChar": 76
      },
      "revId": "e6c21a80a91919707b05ee301de990c660e24b85",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_23da32e8",
        "filename": "tests/unit/network_services/test_utils.py",
        "patchSetId": 7
      },
      "lineNbr": 128,
      "author": {
        "id": 6831
      },
      "writtenOn": "2017-12-14T19:09:02Z",
      "side": 1,
      "message": "it seems that they reconsidered that in PY3:\n\n \u003e\u003e\u003e sys.version\n \u00273.5.2 (default, Aug 18 2017, 17:48:00) \\n[GCC 5.4.0 20160609]\u0027\n \u003e\u003e\u003e be1 \u003d BaseException(\u0027hello world\u0027)\n \u003e\u003e\u003e \u0027message\u0027 in dir(be1)\n False\n \u003e\u003e\u003e be1.args[0]\n \u0027hello world\u0027\n \u003e\u003e\u003e str(be1)\n \u0027hello world\u0027\n\nversus:\n\n \u003e\u003e\u003e sys.version\n \u00272.7.12 (default, Nov 19 2016, 06:48:10) \\n[GCC 5.4.0 20160609]\u0027\n \u003e\u003e\u003e be1 \u003d BaseException(\u0027hello world\u0027)\n \u003e\u003e\u003e \u0027message\u0027 in dir(be1)\n True\n \u003e\u003e\u003e be1.args[0]\n \u0027hello world\u0027\n \u003e\u003e\u003e str(be1)\n \u0027hello world\u0027\n\nthe args attribute is consistent and converting objects to string is essential, as i see things.",
      "parentUuid": "9a3d3df0_63443ab7",
      "range": {
        "startLine": 128,
        "startChar": 49,
        "endLine": 128,
        "endChar": 76
      },
      "revId": "e6c21a80a91919707b05ee301de990c660e24b85",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_c306e685",
        "filename": "tests/unit/network_services/test_utils.py",
        "patchSetId": 7
      },
      "lineNbr": 143,
      "author": {
        "id": 6831
      },
      "writtenOn": "2017-12-14T18:00:44Z",
      "side": 1,
      "message": "as above",
      "range": {
        "startLine": 143,
        "startChar": 49,
        "endLine": 143,
        "endChar": 76
      },
      "revId": "e6c21a80a91919707b05ee301de990c660e24b85",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}