{
  "comments": [
    {
      "key": {
        "uuid": "5a3f45e8_7f60b935",
        "filename": "yardstick/benchmark/runners/base.py",
        "patchSetId": 4
      },
      "lineNbr": 44,
      "author": {
        "id": 5437
      },
      "writtenOn": "2018-02-23T07:19:59Z",
      "side": 1,
      "message": "For PEP8 code check, not sure if it is correct.",
      "range": {
        "startLine": 44,
        "startChar": 11,
        "endLine": 44,
        "endChar": 29
      },
      "revId": "ed30870a1a5823423a44f8fa2ef559526e2849f8",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_6113f25c",
        "filename": "yardstick/benchmark/runners/base.py",
        "patchSetId": 4
      },
      "lineNbr": 44,
      "author": {
        "id": 2311
      },
      "writtenOn": "2018-02-28T10:51:08Z",
      "side": 1,
      "message": "It looks like it is correct, this exception is raised whenever there is a non-zero exit code\n\nhttps://docs.python.org/2/library/subprocess.html#subprocess.check_output",
      "parentUuid": "5a3f45e8_7f60b935",
      "range": {
        "startLine": 44,
        "startChar": 11,
        "endLine": 44,
        "endChar": 29
      },
      "revId": "ed30870a1a5823423a44f8fa2ef559526e2849f8",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}